import { cva } from 'class-variance-authority';

const flexVariants = cva('--flex flex', {
  variants: {
    direction: {
      horizontal: 'flex-row',
      vertical: 'flex-col',
    },
    directionSm: {
      horizontal: 'sm:flex-row',
      vertical: 'sm:flex-col',
    },
    directionMd: {
      horizontal: 'md:flex-row',
      vertical: 'md:flex-col',
    },
    directionLg: {
      horizontal: 'lg:flex-row',
      vertical: 'lg:flex-col',
    },

    wrap: {
      wrap: 'flex-wrap',
      nowrap: 'flex-nowrap',
      reverse: 'flex-wrap-reverse',
    },
    wrapSm: {
      wrap: 'sm:flex-wrap',
      nowrap: 'sm:flex-nowrap',
      reverse: 'sm:flex-wrap-reverse',
    },
    wrapMd: {
      wrap: 'md:flex-wrap',
      nowrap: 'md:flex-nowrap',
      reverse: 'md:flex-wrap-reverse',
    },
    wrapLg: {
      wrap: 'lg:flex-wrap',
      nowrap: 'lg:flex-nowrap',
      reverse: 'lg:flex-wrap-reverse',
    },

    gap: {
      none: 'gap-0',
      normal: 'gap-3',
      sm: 'gap-2',
      lg: 'gap-5',
    },

    justifyContent: {
      normal: 'justify-normal',
      start: 'justify-start',
      end: 'justify-end',
      center: 'justify-center',
      between: 'justify-between',
      evenly: 'justify-evenly',
      around: 'justify-around',
      stretch: 'justify-stretch',
    },
    justifyContentSm: {
      normal: 'sm:justify-normal',
      start: 'sm:justify-start',
      end: 'sm:justify-end',
      center: 'sm:justify-center',
      between: 'sm:justify-between',
      evenly: 'sm:justify-evenly',
      around: 'sm:justify-around',
      stretch: 'sm:justify-stretch',
    },
    justifyContentMd: {
      normal: 'md:justify-normal',
      start: 'md:justify-start',
      end: 'md:justify-end',
      center: 'md:justify-center',
      between: 'md:justify-between',
      evenly: 'md:justify-evenly',
      around: 'md:justify-around',
      stretch: 'md:justify-stretch',
    },
    justifyContentLg: {
      normal: 'lg:justify-normal',
      start: 'lg:justify-start',
      end: 'lg:justify-end',
      center: 'lg:justify-center',
      between: 'lg:justify-between',
      evenly: 'lg:justify-evenly',
      around: 'lg:justify-around',
      stretch: 'lg:justify-stretch',
    },

    justifyItems: {
      start: 'justify-items-start',
      end: 'justify-items-end',
      center: 'justify-items-center',
      stretch: 'justify-items-stretch',
    },
    justifyItemsSm: {
      start: 'sm:justify-items-start',
      end: 'sm:justify-items-end',
      center: 'sm:justify-items-center',
      stretch: 'sm:justify-items-stretch',
    },
    justifyItemsMd: {
      start: 'md:justify-items-start',
      end: 'md:justify-items-end',
      center: 'md:justify-items-center',
      stretch: 'md:justify-items-stretch',
    },
    justifyItemsLg: {
      start: 'lg:justify-items-start',
      end: 'lg:justify-items-end',
      center: 'lg:justify-items-center',
      stretch: 'lg:justify-items-stretch',
    },

    alignContent: {
      normal: 'content-normal',
      center: 'content-center',
      start: 'content-start',
      end: 'content-end',
      between: 'content-between',
      around: 'content-around',
      evenly: 'content-evenly',
      baseline: 'content-baseline',
      stretch: 'content-stretch',
    },
    alignContentSm: {
      normal: 'sm:content-normal',
      center: 'sm:content-center',
      start: 'sm:content-start',
      end: 'sm:content-end',
      between: 'sm:content-between',
      around: 'sm:content-around',
      evenly: 'sm:content-evenly',
      baseline: 'sm:content-baseline',
      stretch: 'sm:content-stretch',
    },
    alignContentMd: {
      normal: 'md:content-normal',
      center: 'md:content-center',
      start: 'md:content-start',
      end: 'md:content-end',
      between: 'md:content-between',
      around: 'md:content-around',
      evenly: 'md:content-evenly',
      baseline: 'md:content-baseline',
      stretch: 'md:content-stretch',
    },
    alignContentLg: {
      normal: 'lg:content-normal',
      center: 'lg:content-center',
      start: 'lg:content-start',
      end: 'lg:content-end',
      between: 'lg:content-between',
      around: 'lg:content-around',
      evenly: 'lg:content-evenly',
      baseline: 'lg:content-baseline',
      stretch: 'lg:content-stretch',
    },

    alignItems: {
      start: 'items-start',
      end: 'items-end',
      center: 'items-center',
      baseline: 'items-baseline',
      stretch: 'items-stretch',
    },
    alignItemsSm: {
      start: 'sm:items-start',
      end: 'sm:items-end',
      center: 'sm:items-center',
      baseline: 'sm:items-baseline',
      stretch: 'sm:items-stretch',
    },
    alignItemsMd: {
      start: 'md:items-start',
      end: 'md:items-end',
      center: 'md:items-center',
      baseline: 'md:items-baseline',
      stretch: 'md:items-stretch',
    },
    alignItemsLg: {
      start: 'lg:items-start',
      end: 'lg:items-end',
      center: 'lg:items-center',
      baseline: 'lg:items-baseline',
      stretch: 'lg:items-stretch',
    },

    placeContent: {
      center: 'place-content-center',
      start: 'place-content-start',
      end: 'place-content-end',
      between: 'place-content-between',
      around: 'place-content-around',
      evenly: 'place-content-evenly',
      baseline: 'place-content-baseline',
      stretch: 'place-content-stretch',
    },
    placeContentSm: {
      center: 'sm:place-content-center',
      start: 'sm:place-content-start',
      end: 'sm:place-content-end',
      between: 'sm:place-content-between',
      around: 'sm:place-content-around',
      evenly: 'sm:place-content-evenly',
      baseline: 'sm:place-content-baseline',
      stretch: 'sm:place-content-stretch',
    },
    placeContentMd: {
      center: 'md:place-content-center',
      start: 'md:place-content-start',
      end: 'md:place-content-end',
      between: 'md:place-content-between',
      around: 'md:place-content-around',
      evenly: 'md:place-content-evenly',
      baseline: 'md:place-content-baseline',
      stretch: 'md:place-content-stretch',
    },
    placeContentLg: {
      center: 'lg:place-content-center',
      start: 'lg:place-content-start',
      end: 'lg:place-content-end',
      between: 'lg:place-content-between',
      around: 'lg:place-content-around',
      evenly: 'lg:place-content-evenly',
      baseline: 'lg:place-content-baseline',
      stretch: 'lg:place-content-stretch',
    },

    placeItems: {
      start: 'place-items-start',
      end: 'place-items-end',
      center: 'place-items-center',
      baseline: 'place-items-baseline',
      stretch: 'place-items-stretch',
    },
    placeItemsSm: {
      start: 'sm:place-items-start',
      end: 'sm:place-items-end',
      center: 'sm:place-items-center',
      baseline: 'sm:place-items-baseline',
      stretch: 'sm:place-items-stretch',
    },
    placeItemsMd: {
      start: 'md:place-items-start',
      end: 'md:place-items-end',
      center: 'md:place-items-center',
      baseline: 'md:place-items-baseline',
      stretch: 'md:place-items-stretch',
    },
    placeItemsLg: {
      start: 'lg:place-items-start',
      end: 'lg:place-items-end',
      center: 'lg:place-items-center',
      baseline: 'lg:place-items-baseline',
      stretch: 'lg:place-items-stretch',
    },
  },
  defaultVariants: {
    direction: 'horizontal',
    gap: 'none',
  },
});

const flexItemVariants = cva('--flex-item', {
  variants: {
    justifySelf: {
      auto: 'justify-self-auto',
      start: 'justify-self-start',
      end: 'justify-self-end',
      center: 'justify-self-center',
      stretch: 'justify-self-stretch',
    },
    justifySelfSm: {
      auto: 'sm:justify-self-auto',
      start: 'sm:justify-self-start',
      end: 'sm:justify-self-end',
      center: 'sm:justify-self-center',
      stretch: 'sm:justify-self-stretch',
    },
    justifySelfMd: {
      auto: 'md:justify-self-auto',
      start: 'md:justify-self-start',
      end: 'md:justify-self-end',
      center: 'md:justify-self-center',
      stretch: 'md:justify-self-stretch',
    },
    justifySelfLg: {
      auto: 'lg:justify-self-auto',
      start: 'lg:justify-self-start',
      end: 'lg:justify-self-end',
      center: 'lg:justify-self-center',
      stretch: 'lg:justify-self-stretch',
    },

    alignSelf: {
      auto: 'self-auto',
      start: 'self-start',
      end: 'self-end',
      center: 'self-center',
      stretch: 'self-stretch',
      baseline: 'self-baseline',
    },
    alignSelfSm: {
      auto: 'sm:self-auto',
      start: 'sm:self-start',
      end: 'sm:self-end',
      center: 'sm:self-center',
      stretch: 'sm:self-stretch',
      baseline: 'sm:self-baseline',
    },
    alignSelfMd: {
      auto: 'md:self-auto',
      start: 'md:self-start',
      end: 'md:self-end',
      center: 'md:self-center',
      stretch: 'md:self-stretch',
      baseline: 'md:self-baseline',
    },
    alignSelfLg: {
      auto: 'lg:self-auto',
      start: 'lg:self-start',
      end: 'lg:self-end',
      center: 'lg:self-center',
      stretch: 'lg:self-stretch',
      baseline: 'lg:self-baseline',
    },

    placeSelf: {
      auto: 'place-self-auto',
      start: 'place-self-start',
      end: 'place-self-end',
      center: 'place-self-center',
      stretch: 'place-self-stretch',
    },
    placeSelfSm: {
      auto: 'sm:place-self-auto',
      start: 'sm:place-self-start',
      end: 'sm:place-self-end',
      center: 'sm:place-self-center',
      stretch: 'sm:place-self-stretch',
    },
    placeSelfMd: {
      auto: 'md:place-self-auto',
      start: 'md:place-self-start',
      end: 'md:place-self-end',
      center: 'md:place-self-center',
      stretch: 'md:place-self-stretch',
    },
    placeSelfLg: {
      auto: 'lg:place-self-auto',
      start: 'lg:place-self-start',
      end: 'lg:place-self-end',
      center: 'lg:place-self-center',
      stretch: 'lg:place-self-stretch',
    },

    flex: {
      auto: 'flex-auto',
      initial: 'flex-initial',
      none: 'flex-none',
      1: 'flex-1',
      2: 'flex-2',
      3: 'flex-3',
      4: 'flex-4',
      5: 'flex-5',
      6: 'flex-6',
      7: 'flex-7',
      8: 'flex-8',
      9: 'flex-9',
      10: 'flex-10',
    },
    flexSm: {
      auto: 'sm:flex-auto',
      initial: 'sm:flex-initial',
      none: 'sm:flex-none',
      1: 'sm:flex-1',
      2: 'sm:flex-2',
      3: 'sm:flex-3',
      4: 'sm:flex-4',
      5: 'sm:flex-5',
      6: 'sm:flex-6',
      7: 'sm:flex-7',
      8: 'sm:flex-8',
      9: 'sm:flex-9',
      10: 'sm:flex-10',
    },
    flexMd: {
      auto: 'md:flex-auto',
      initial: 'md:flex-initial',
      none: 'md:flex-none',
      1: 'md:flex-1',
      2: 'md:flex-2',
      3: 'md:flex-3',
      4: 'md:flex-4',
      5: 'md:flex-5',
      6: 'md:flex-6',
      7: 'md:flex-7',
      8: 'md:flex-8',
      9: 'md:flex-9',
      10: 'md:flex-10',
    },
    flexLg: {
      auto: 'lg:flex-auto',
      initial: 'lg:flex-initial',
      none: 'lg:flex-none',
      1: 'lg:flex-1',
      2: 'lg:flex-2',
      3: 'lg:flex-3',
      4: 'lg:flex-4',
      5: 'lg:flex-5',
      6: 'lg:flex-6',
      7: 'lg:flex-7',
      8: 'lg:flex-8',
      9: 'lg:flex-9',
      10: 'lg:flex-10',
    },
  },
});

export { flexItemVariants, flexVariants };
