import { cva } from 'class-variance-authority';

const gridVariants = cva('--grid grid', {
  variants: {
    columns: {
      1: 'grid-cols-1',
      2: 'grid-cols-2',
      3: 'grid-cols-3',
      4: 'grid-cols-4',
      5: 'grid-cols-5',
      6: 'grid-cols-6',
      7: 'grid-cols-7',
      8: 'grid-cols-8',
      9: 'grid-cols-9',
      10: 'grid-cols-10',
      11: 'grid-cols-11',
      12: 'grid-cols-12',
    },
    columnsSm: {
      1: 'sm:grid-cols-1',
      2: 'sm:grid-cols-2',
      3: 'sm:grid-cols-3',
      4: 'sm:grid-cols-4',
      5: 'sm:grid-cols-5',
      6: 'sm:grid-cols-6',
      7: 'sm:grid-cols-7',
      8: 'sm:grid-cols-8',
      9: 'sm:grid-cols-9',
      10: 'sm:grid-cols-10',
      11: 'sm:grid-cols-11',
      12: 'sm:grid-cols-12',
    },
    columnsMd: {
      1: 'md:grid-cols-1',
      2: 'md:grid-cols-2',
      3: 'md:grid-cols-3',
      4: 'md:grid-cols-4',
      5: 'md:grid-cols-5',
      6: 'md:grid-cols-6',
      7: 'md:grid-cols-7',
      8: 'md:grid-cols-8',
      9: 'md:grid-cols-9',
      10: 'md:grid-cols-10',
      11: 'md:grid-cols-11',
      12: 'md:grid-cols-12',
    },
    columnsLg: {
      1: 'lg:grid-cols-1',
      2: 'lg:grid-cols-2',
      3: 'lg:grid-cols-3',
      4: 'lg:grid-cols-4',
      5: 'lg:grid-cols-5',
      6: 'lg:grid-cols-6',
      7: 'lg:grid-cols-7',
      8: 'lg:grid-cols-8',
      9: 'lg:grid-cols-9',
      10: 'lg:grid-cols-10',
      11: 'lg:grid-cols-11',
      12: 'lg:grid-cols-12',
    },

    justifyContent: {
      normal: 'justify-normal',
      start: 'justify-start',
      end: 'justify-end',
      center: 'justify-center',
      between: 'justify-between',
      evenly: 'justify-evenly',
      around: 'justify-around',
      stretch: 'justify-stretch',
    },
    justifyContentSm: {
      normal: 'sm:justify-normal',
      start: 'sm:justify-start',
      end: 'sm:justify-end',
      center: 'sm:justify-center',
      between: 'sm:justify-between',
      evenly: 'sm:justify-evenly',
      around: 'sm:justify-around',
      stretch: 'sm:justify-stretch',
    },
    justifyContentMd: {
      normal: 'md:justify-normal',
      start: 'md:justify-start',
      end: 'md:justify-end',
      center: 'md:justify-center',
      between: 'md:justify-between',
      evenly: 'md:justify-evenly',
      around: 'md:justify-around',
      stretch: 'md:justify-stretch',
    },
    justifyContentLg: {
      normal: 'lg:justify-normal',
      start: 'lg:justify-start',
      end: 'lg:justify-end',
      center: 'lg:justify-center',
      between: 'lg:justify-between',
      evenly: 'lg:justify-evenly',
      around: 'lg:justify-around',
      stretch: 'lg:justify-stretch',
    },

    justifyItems: {
      start: 'justify-items-start',
      end: 'justify-items-end',
      center: 'justify-items-center',
      stretch: 'justify-items-stretch',
    },
    justifyItemsSm: {
      start: 'sm:justify-items-start',
      end: 'sm:justify-items-end',
      center: 'sm:justify-items-center',
      stretch: 'sm:justify-items-stretch',
    },
    justifyItemsMd: {
      start: 'md:justify-items-start',
      end: 'md:justify-items-end',
      center: 'md:justify-items-center',
      stretch: 'md:justify-items-stretch',
    },
    justifyItemsLg: {
      start: 'lg:justify-items-start',
      end: 'lg:justify-items-end',
      center: 'lg:justify-items-center',
      stretch: 'lg:justify-items-stretch',
    },

    alignContent: {
      normal: 'content-normal',
      center: 'content-center',
      start: 'content-start',
      end: 'content-end',
      between: 'content-between',
      around: 'content-around',
      evenly: 'content-evenly',
      baseline: 'content-baseline',
      stretch: 'content-stretch',
    },
    alignContentSm: {
      normal: 'sm:content-normal',
      center: 'sm:content-center',
      start: 'sm:content-start',
      end: 'sm:content-end',
      between: 'sm:content-between',
      around: 'sm:content-around',
      evenly: 'sm:content-evenly',
      baseline: 'sm:content-baseline',
      stretch: 'sm:content-stretch',
    },
    alignContentMd: {
      normal: 'md:content-normal',
      center: 'md:content-center',
      start: 'md:content-start',
      end: 'md:content-end',
      between: 'md:content-between',
      around: 'md:content-around',
      evenly: 'md:content-evenly',
      baseline: 'md:content-baseline',
      stretch: 'md:content-stretch',
    },
    alignContentLg: {
      normal: 'lg:content-normal',
      center: 'lg:content-center',
      start: 'lg:content-start',
      end: 'lg:content-end',
      between: 'lg:content-between',
      around: 'lg:content-around',
      evenly: 'lg:content-evenly',
      baseline: 'lg:content-baseline',
      stretch: 'lg:content-stretch',
    },

    alignItems: {
      start: 'items-start',
      end: 'items-end',
      center: 'items-center',
      baseline: 'items-baseline',
      stretch: 'items-stretch',
    },
    alignItemsSm: {
      start: 'sm:items-start',
      end: 'sm:items-end',
      center: 'sm:items-center',
      baseline: 'sm:items-baseline',
      stretch: 'sm:items-stretch',
    },
    alignItemsMd: {
      start: 'md:items-start',
      end: 'md:items-end',
      center: 'md:items-center',
      baseline: 'md:items-baseline',
      stretch: 'md:items-stretch',
    },
    alignItemsLg: {
      start: 'lg:items-start',
      end: 'lg:items-end',
      center: 'lg:items-center',
      baseline: 'lg:items-baseline',
      stretch: 'lg:items-stretch',
    },

    placeContent: {
      center: 'place-content-center',
      start: 'place-content-start',
      end: 'place-content-end',
      between: 'place-content-between',
      around: 'place-content-around',
      evenly: 'place-content-evenly',
      baseline: 'place-content-baseline',
      stretch: 'place-content-stretch',
    },
    placeContentSm: {
      center: 'sm:place-content-center',
      start: 'sm:place-content-start',
      end: 'sm:place-content-end',
      between: 'sm:place-content-between',
      around: 'sm:place-content-around',
      evenly: 'sm:place-content-evenly',
      baseline: 'sm:place-content-baseline',
      stretch: 'sm:place-content-stretch',
    },
    placeContentMd: {
      center: 'md:place-content-center',
      start: 'md:place-content-start',
      end: 'md:place-content-end',
      between: 'md:place-content-between',
      around: 'md:place-content-around',
      evenly: 'md:place-content-evenly',
      baseline: 'md:place-content-baseline',
      stretch: 'md:place-content-stretch',
    },
    placeContentLg: {
      center: 'lg:place-content-center',
      start: 'lg:place-content-start',
      end: 'lg:place-content-end',
      between: 'lg:place-content-between',
      around: 'lg:place-content-around',
      evenly: 'lg:place-content-evenly',
      baseline: 'lg:place-content-baseline',
      stretch: 'lg:place-content-stretch',
    },

    placeItems: {
      start: 'place-items-start',
      end: 'place-items-end',
      center: 'place-items-center',
      baseline: 'place-items-baseline',
      stretch: 'place-items-stretch',
    },
    placeItemsSm: {
      start: 'sm:place-items-start',
      end: 'sm:place-items-end',
      center: 'sm:place-items-center',
      baseline: 'sm:place-items-baseline',
      stretch: 'sm:place-items-stretch',
    },
    placeItemsMd: {
      start: 'md:place-items-start',
      end: 'md:place-items-end',
      center: 'md:place-items-center',
      baseline: 'md:place-items-baseline',
      stretch: 'md:place-items-stretch',
    },
    placeItemsLg: {
      start: 'lg:place-items-start',
      end: 'lg:place-items-end',
      center: 'lg:place-items-center',
      baseline: 'lg:place-items-baseline',
      stretch: 'lg:place-items-stretch',
    },

    gap: {
      none: 'gap-0',
      normal: 'gap-3',
      sm: 'gap-2',
      lg: 'gap-5',
    },
  },
  defaultVariants: {
    columns: 4,
    gap: 'none',
  },
});

const gridItemVariants = cva('--grid-item', {
  variants: {
    colSpan: {
      1: 'col-span-1',
      2: 'col-span-2',
      3: 'col-span-3',
      4: 'col-span-4',
      5: 'col-span-5',
      6: 'col-span-6',
      7: 'col-span-7',
      8: 'col-span-8',
      9: 'col-span-9',
      10: 'col-span-10',
      11: 'col-span-11',
      12: 'col-span-12',
    },
    colSpanSm: {
      1: 'sm:col-span-1',
      2: 'sm:col-span-2',
      3: 'sm:col-span-3',
      4: 'sm:col-span-4',
      5: 'sm:col-span-5',
      6: 'sm:col-span-6',
      7: 'sm:col-span-7',
      8: 'sm:col-span-8',
      9: 'sm:col-span-9',
      10: 'sm:col-span-10',
      11: 'sm:col-span-11',
      12: 'sm:col-span-12',
    },
    colSpanMd: {
      1: 'md:col-span-1',
      2: 'md:col-span-2',
      3: 'md:col-span-3',
      4: 'md:col-span-4',
      5: 'md:col-span-5',
      6: 'md:col-span-6',
      7: 'md:col-span-7',
      8: 'md:col-span-8',
      9: 'md:col-span-9',
      10: 'md:col-span-10',
      11: 'md:col-span-11',
      12: 'md:col-span-12',
    },
    colSpanLg: {
      1: 'lg:col-span-1',
      2: 'lg:col-span-2',
      3: 'lg:col-span-3',
      4: 'lg:col-span-4',
      5: 'lg:col-span-5',
      6: 'lg:col-span-6',
      7: 'lg:col-span-7',
      8: 'lg:col-span-8',
      9: 'lg:col-span-9',
      10: 'lg:col-span-10',
      11: 'lg:col-span-11',
      12: 'lg:col-span-12',
    },

    rowSpan: {
      1: 'row-span-1',
      2: 'row-span-2',
      3: 'row-span-3',
      4: 'row-span-4',
      5: 'row-span-5',
      6: 'row-span-6',
      7: 'row-span-7',
      8: 'row-span-8',
      9: 'row-span-9',
      10: 'row-span-10',
      11: 'row-span-11',
      12: 'row-span-12',
    },
    rowSpanSm: {
      1: 'sm:row-span-1',
      2: 'sm:row-span-2',
      3: 'sm:row-span-3',
      4: 'sm:row-span-4',
      5: 'sm:row-span-5',
      6: 'sm:row-span-6',
      7: 'sm:row-span-7',
      8: 'sm:row-span-8',
      9: 'sm:row-span-9',
      10: 'sm:row-span-10',
      11: 'sm:row-span-11',
      12: 'sm:row-span-12',
    },
    rowSpanMd: {
      1: 'md:row-span-1',
      2: 'md:row-span-2',
      3: 'md:row-span-3',
      4: 'md:row-span-4',
      5: 'md:row-span-5',
      6: 'md:row-span-6',
      7: 'md:row-span-7',
      8: 'md:row-span-8',
      9: 'md:row-span-9',
      10: 'md:row-span-10',
      11: 'md:row-span-11',
      12: 'md:row-span-12',
    },
    rowSpanLg: {
      1: 'lg:row-span-1',
      2: 'lg:row-span-2',
      3: 'lg:row-span-3',
      4: 'lg:row-span-4',
      5: 'lg:row-span-5',
      6: 'lg:row-span-6',
      7: 'lg:row-span-7',
      8: 'lg:row-span-8',
      9: 'lg:row-span-9',
      10: 'lg:row-span-10',
      11: 'lg:row-span-11',
      12: 'lg:row-span-12',
    },

    justifySelf: {
      auto: 'justify-self-auto',
      start: 'justify-self-start',
      end: 'justify-self-end',
      center: 'justify-self-center',
      stretch: 'justify-self-stretch',
    },
    justifySelfSm: {
      auto: 'sm:justify-self-auto',
      start: 'sm:justify-self-start',
      end: 'sm:justify-self-end',
      center: 'sm:justify-self-center',
      stretch: 'sm:justify-self-stretch',
    },
    justifySelfMd: {
      auto: 'md:justify-self-auto',
      start: 'md:justify-self-start',
      end: 'md:justify-self-end',
      center: 'md:justify-self-center',
      stretch: 'md:justify-self-stretch',
    },
    justifySelfLg: {
      auto: 'lg:justify-self-auto',
      start: 'lg:justify-self-start',
      end: 'lg:justify-self-end',
      center: 'lg:justify-self-center',
      stretch: 'lg:justify-self-stretch',
    },

    alignSelf: {
      auto: 'self-auto',
      start: 'self-start',
      end: 'self-end',
      center: 'self-center',
      stretch: 'self-stretch',
      baseline: 'self-baseline',
    },
    alignSelfSm: {
      auto: 'sm:self-auto',
      start: 'sm:self-start',
      end: 'sm:self-end',
      center: 'sm:self-center',
      stretch: 'sm:self-stretch',
      baseline: 'sm:self-baseline',
    },
    alignSelfMd: {
      auto: 'md:self-auto',
      start: 'md:self-start',
      end: 'md:self-end',
      center: 'md:self-center',
      stretch: 'md:self-stretch',
      baseline: 'md:self-baseline',
    },
    alignSelfLg: {
      auto: 'lg:self-auto',
      start: 'lg:self-start',
      end: 'lg:self-end',
      center: 'lg:self-center',
      stretch: 'lg:self-stretch',
      baseline: 'lg:self-baseline',
    },

    placeSelf: {
      auto: 'place-self-auto',
      start: 'place-self-start',
      end: 'place-self-end',
      center: 'place-self-center',
      stretch: 'place-self-stretch',
    },
    placeSelfSm: {
      auto: 'sm:place-self-auto',
      start: 'sm:place-self-start',
      end: 'sm:place-self-end',
      center: 'sm:place-self-center',
      stretch: 'sm:place-self-stretch',
    },
    placeSelfMd: {
      auto: 'md:place-self-auto',
      start: 'md:place-self-start',
      end: 'md:place-self-end',
      center: 'md:place-self-center',
      stretch: 'md:place-self-stretch',
    },
    placeSelfLg: {
      auto: 'lg:place-self-auto',
      start: 'lg:place-self-start',
      end: 'lg:place-self-end',
      center: 'lg:place-self-center',
      stretch: 'lg:place-self-stretch',
    },
  },
});

export { gridItemVariants, gridVariants };
